#!/usr/bin/env python3
# Checks memory fragmentation
import subprocess

import _discord
import _logging

logger = _logging.configure_logger(log_file="/var/log/memory-fragmentation.log")


if __name__ == "__main__":
    msg = "Checking memory fragmentation"
    logger.info(msg)
    _discord.notify_discord(msg)

    result = subprocess.run(
        ["cat", "/sys/kernel/debug/extfrag/extfrag_index"],
        capture_output=True,
        text=True,
    )
    logger.debug(f"{result=}")

    msg = f"memory fragmentation:\n\n{result.stdout}"
    logger.info(msg)
    _discord.notify_discord(msg)
