#!/usr/bin/env python3
"""Analyzes data gathered by disk-utilization-gatherer"""

import datetime
import gzip
import json
import logging
import os
import statistics
import subprocess
import sys
from dataclasses import dataclass

import _logging
import _discord
import _smart

logger = _logging.configure_logger(log_file="/var/log/disk-utilization.log")

try:
    from tabulate import tabulate

    TABULATE_AVAILABLE = True
except ImportError:
    logger.warning(f"tabulate not available, will not format output as table")
    TABULATE_AVAILABLE = False

# Try yesterday's logs first - then today's
SOURCE_LOG_OPTIONS = (
    "/var/log/disk-utilization-stats.log.1",
    "/var/log/disk-utilization-stats.log.1.gz",
    "/var/log/disk-utilization-stats.log",
)


@dataclass
class DeviceStats:
    name: str
    timestamps: list[float | int]
    util_values: list[float | int]

    def max_util(self) -> float:
        return max(self.util_values)

    def min_util(self) -> float:
        return min(self.util_values)

    def avg_util(self) -> float:
        return statistics.mean(self.util_values)

    def median_util(self) -> float:
        return statistics.median(self.util_values)

    def max_util_and_timestamp(self) -> tuple[float, float]:
        max_value = self.max_util()
        max_index = self.util_values.index(max_value)
        return max_value, self.timestamps[max_index]

    def min_util_and_timestamp(self) -> tuple[float, float]:
        min_value = self.min_util()
        return min_value, self.timestamps[self.util_values.index(min_value)]

    def status_warning(self) -> bool:
        return (
            self.max_util() >= 99 or self.avg_util() >= 50 or self.median_util() >= 50
        )

    def status_critical(self) -> bool:
        return self.avg_util() >= 95 or self.median_util() >= 95


def main():
    source_log = ""
    for f in SOURCE_LOG_OPTIONS:
        if os.path.exists(f):
            source_log = f
            break
    if not source_log:
        logger.error(f"No source log file found, looking for: {SOURCE_LOG_OPTIONS}")
        sys.exit(1)

    logger.info(f"Reading from {source_log}")
    if source_log.endswith(".gz"):
        log_contents = gzip.open(source_log, "rt").read()
    else:
        log_contents = open(source_log, "r").read()

    earliest_timestamp = float("inf")
    latest_timestamp = 0
    datapoints = 0
    parsed_stats: dict[str, DeviceStats] = {}
    for line in log_contents.splitlines():
        try:
            timestamp, name, util_value = line.split(",")
        except ValueError:
            continue
        if not name in parsed_stats:
            parsed_stats[name] = DeviceStats(name=name, timestamps=[], util_values=[])
        datapoints += 1
        timestamp = float(timestamp)
        earliest_timestamp = min(earliest_timestamp, timestamp)
        latest_timestamp = max(latest_timestamp, timestamp)
        parsed_stats[name].timestamps.append(timestamp)
        parsed_stats[name].util_values.append(float(util_value))

    logger.info(f"Parsed {datapoints} datapoints")
    logger.info(
        f"Data from {timestamp_as_string(earliest_timestamp)} to {timestamp_as_string(latest_timestamp)}"
    )
    logger.info(f"Disk utilization stats:")
    discord_msg = [
        f"Disk utilization stats from {timestamp_as_string(earliest_timestamp)} to {timestamp_as_string(latest_timestamp)} ({datapoints} datapoints)",
        "```",
    ]
    warning_devices = []
    critical_devices = []
    first_device = True
    for device, stats in parsed_stats.items():
        if not first_device:
            discord_msg.append("")
        first_device = False
        max_util, max_util_timestamp = stats.max_util_and_timestamp()
        _disk_name = device + " - " + disk_name(f"/dev/{device}")
        log_level = logging.INFO
        if stats.status_critical():
            critical_devices.append(_disk_name)
            _disk_name = f"{_disk_name} *CRITICAL*"
            log_level = logging.ERROR
        elif stats.status_warning():
            warning_devices.append(_disk_name)
            _disk_name = f"{_disk_name} WARNING"
            log_level = logging.WARNING
        logger.log(log_level, f"{_disk_name}")
        discord_msg.append(f"{_disk_name}")
        logger.log(log_level, f"Min:    {stats.min_util():.2f} %")
        logger.log(
            log_level,
            f"Max:    {max_util:.2f} % (at {timestamp_as_string(max_util_timestamp)})",
        )
        discord_msg.append(f"avg {stats.avg_util():.2f} %, max {max_util:.2f} %")
        logger.log(log_level, f"Avg:    {stats.avg_util():.2f} %")
        logger.log(log_level, f"Median: {stats.median_util():.2f} %")

    discord_msg.append("```")
    if critical_devices:
        discord_msg.insert(1, f"**CRITICAL DEVICES**: {", ".join(critical_devices)}")
    if warning_devices:
        discord_msg.insert(1, f"**WARNING DEVICES**: {", ".join(warning_devices)}")
    _discord.notify_discord(
        "\n".join(discord_msg), is_error=bool(warning_devices or critical_devices)
    )


def is_actual_disk(device: str) -> bool:
    """iostat contains loop devices, we don't care about those"""
    return device.startswith("sd") or device.startswith("nvme")


def timestamp_as_string(timestamp: float) -> str:
    return datetime.datetime.fromtimestamp(timestamp).strftime("%Y-%m-%d %H:%M:%S")


def disk_name(device: str) -> str:
    return (
        _smart.human_readable_name(_smart.device_info(device))
        + f" - {first_mount_point(device)}"
    )


def first_mount_point(device: str) -> str:
    if not device.startswith("/dev/"):
        device = f"/dev/{device}"
    # Scan each partition until a mount point is found
    partitions = (
        subprocess.check_output(
            ["partx", "--noheadings", "--output", "nr", "--show", device]
        )
        .decode("utf-8")
        .split()
    )
    for partition_number in partitions:
        if device.startswith("/dev/sd"):
            partition = f"{device}{partition_number}"
        elif "nvme" in device:
            partition = f"{device}p{partition_number}"
        else:
            return "(unknown device)"
        try:
            output = subprocess.check_output(
                ["findmnt", "--json", "--source", partition]
            ).decode("utf-8")
            return json.loads(output)["filesystems"][0]["target"]
        except subprocess.CalledProcessError:
            continue
    return "(unknown device)"


if __name__ == "__main__":
    main()
